import AppKit
import SwiftUI

/// Displays the bundled third-party notices.
///
/// The notices are read from the app bundle rather than compiled into a string
/// so that regenerating them with `scripts/make-notices.py` is enough to keep
/// this accurate. Both MIT and Apache 2.0 require these notices to travel with
/// binary distributions, so the file must be inside the `.app`, not merely in
/// the repository.
struct AcknowledgementsView: View {

    static let resourceName = "THIRD-PARTY-NOTICES"

    var body: some View {
        VStack(alignment: .leading, spacing: 0) {
            ScrollView {
                Text(Self.notices)
                    .font(.system(size: 11, design: .monospaced))
                    .textSelection(.enabled)
                    .frame(maxWidth: .infinity, alignment: .leading)
                    .padding(16)
            }
        }
        .frame(width: 620, height: 520)
    }

    private static var notices: String {
        guard let url = Bundle.main.url(forResource: resourceName, withExtension: "txt"),
              let text = try? String(contentsOf: url, encoding: .utf8)
        else {
            Log.error("acknowledgements: notices file not found in bundle")
            return """
            The third-party notices file is missing from this build.

            It is generated by scripts/make-notices.py and copied into the
            application bundle by scripts/build-app.sh.
            """
        }
        Log.info("acknowledgements: loaded \(text.count) characters")
        return text
    }
}
